name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install -g lighthouse
          npm install -g pa11y-ci
          npm install -g html-validate

      - name: Validate HTML
        run: |
          html-validate index.html

      - name: Run Accessibility Tests
        run: |
          pa11y-ci --json --reporter json > pa11y-report.json || true

      - name: Run Lighthouse CI
        run: |
          lighthouse --output=json --output-path=./lighthouse-report.json --chrome-flags="--headless" https://futurodevjunior.github.io/Dolar/ || true

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: lighthouse-report.json

      - name: Upload Pa11y Report
        uses: actions/upload-artifact@v3
        with:
          name: pa11y-report
          path: pa11y-report.json

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Deploy successful!"
          echo "🌐 Site: https://futurodevjunior.github.io/Dolar/"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deploy failed!"
          echo "Check the logs for details"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
